"""added team models

Revision ID: 034635211a2b
Revises: 565286503086
Create Date: 2020-07-29 18:15:01.126913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '034635211a2b'
down_revision = '565286503086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    # ### end Alembic commands ###
