"""added name and company models

Revision ID: 2a64e12fb795
Revises: 034635211a2b
Create Date: 2020-07-30 21:10:26.103936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a64e12fb795'
down_revision = '034635211a2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_status', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_city', sa.String(), nullable=True),
    sa.Column('company_state', sa.String(), nullable=True),
    sa.Column('company_zip_code', sa.Integer(), nullable=True),
    sa.Column('company_phone', sa.String(), nullable=True),
    sa.Column('company_website', sa.String(), nullable=True),
    sa.Column('company_date_created', sa.DateTime(), nullable=True),
    sa.Column('name_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['name_id'], ['name.name_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('name',
    sa.Column('name_id', sa.Integer(), nullable=False),
    sa.Column('name_status', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('name_phone', sa.String(), nullable=True),
    sa.Column('name_email', sa.String(), nullable=True),
    sa.Column('name_city', sa.String(), nullable=True),
    sa.Column('name_state', sa.String(), nullable=True),
    sa.Column('name_zip_code', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name_date_created', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('name_id')
    )
    op.add_column('user', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'team', ['team_id'], ['team_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'team_id')
    op.drop_table('name')
    op.drop_table('company')
    # ### end Alembic commands ###
