"""added name and company models_v2

Revision ID: 7e9c0b02c377
Revises: 2a64e12fb795
Create Date: 2020-07-30 21:21:19.140516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e9c0b02c377'
down_revision = '2a64e12fb795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_status', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_city', sa.String(), nullable=True),
    sa.Column('company_state', sa.String(), nullable=True),
    sa.Column('company_zip_code', sa.Integer(), nullable=True),
    sa.Column('company_phone', sa.String(), nullable=True),
    sa.Column('company_website', sa.String(), nullable=True),
    sa.Column('company_date_created', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('name',
    sa.Column('name_id', sa.Integer(), nullable=False),
    sa.Column('name_status', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('name_phone', sa.String(), nullable=True),
    sa.Column('name_email', sa.String(), nullable=True),
    sa.Column('name_city', sa.String(), nullable=True),
    sa.Column('name_state', sa.String(), nullable=True),
    sa.Column('name_zip_code', sa.Integer(), nullable=True),
    sa.Column('name_date_created', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('name_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('name')
    op.drop_table('company')
    # ### end Alembic commands ###
